# Generated by Django 3.1.5 on 2021-01-19 15:36

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200105_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body_de',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_es',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_fr',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_nl',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
